const ProjectsData = [
  {
    id: 1,
    title: 'Drink Master',
    description:
      'A website for searching cocktails and creating your own recipes.',
    role: [' Scrum-master', 'Developer'],
    technologies: [
      'HTML',
      'SASS',
      'JS',
      'REST API',
      'React',
      'Redux',
      'Node.js',
    ],
    img: '../img/drinkMaster/drinkMaster4.jpg',
    link: 'https://dibaranovska.github.io/projectTeam7/welcome',
    anotherImg: [
      '../img/drinkMaster/drinkMaster4.jpg',
      '../img/drinkMaster/drinkMaster1.jpg',
      '../img/drinkMaster/drinkMaster2.jpg',
      '../img/drinkMaster/drinkMaster3.jpg',
      '../img/drinkMaster/drinkMaster5.jpg',
      '../img/drinkMaster/drinkMaster6.jpg',
    ],
  },
  {
    id: 2,
    title: 'Books',
    description:
      'Application for choosing books with the ability to sort by categories, userauthorization, adding books to favorites. Responsive layout, attractive design.',
    role: [' Scrum-master', 'Developer'],
    technologies: [
      'HTML5',
      'SASS',
      'JS',
      'Handlebars',
      'REST API',
      'AJAX',
      'Parcel',
    ],
    img: '../img/books/books1.jpg',
    link: 'https://slipuykamin.github.io/books-project/index.html',
    anotherImg: [
      '../img/books/books1.jpg',
      '../img/books/books2.jpg',
      '../img/books/books3.jpg',
      '../img/books/books4.jpg',
    ],
  },
  {
    id: 3,
    title: 'Web Studio',
    description: 'A website with hybrid (responsive-adaptive) layout.',
    role: ['Personal project'],
    technologies: ['HTML5', 'SASS', 'JS'],
    img: '../img/web-studio/web-studio.jpg',
    link: 'https://vasheslav.github.io/goit-markup-hw-08/',
    anotherImg: [
      '../img/web-studio/web-studio.jpg',
      '../img/web-studio/web-studio1.jpg',
      '../img/web-studio/web-studio2.jpg',
      '../img/web-studio/web-studio3.jpg',
      '../img/web-studio/web-studio4.jpg',
      '../img/web-studio/web-studio5.jpg',
    ],
  },
  {
    id: 4,
    title: 'Ice Cream',
    description: '',
    role: [' Scrum-master', 'Developer'],
    technologies: ['HTML5', 'SASS', 'JS'],
    img: '../img/iceCream/iceCream1.jpg',
    link: 'https://anna010622.github.io/team-project/',
    anotherImg: [
      '../img/iceCream/iceCream1.jpg',
      '../img/iceCream/iceCream2.jpg',
      '../img/iceCream/iceCream3.jpg',
    ],
  },
];

export default ProjectsData;
