const ProjectsData = [
  {
    id: 1,
    title: 'Drink Master',
    description:
      'A website for searching cocktails and creating your own recipes.',
    role: [' Scrum-master', 'Developer'],
    technologies: [
      'HTML',
      'SASS',
      'JS',
      'REST API',
      'React',
      'Redux',
      'Node.js',
    ],
    img: require('../img/drinkMaster/drink5.png'),
    link: 'https://dibaranovska.github.io/projectTeam7/welcome',
    anotherImg: [
      require('../img/drinkMaster/drink5.png'),
      require('../img/drinkMaster/drink1.png'),
      require('../img/drinkMaster/drink2.png'),
      require('../img/drinkMaster/drink3.png'),
      require('../img/drinkMaster/drink4.png'),
      // require('../img/drinkMaster/drinkMaster6.jpg'),
    ],
  },
  {
    id: 2,
    title: 'Books',
    description:
      'Application for choosing books with the ability to sort by categories, userauthorization, adding books to favorites. Responsive layout, attractive design.',
    role: [' Scrum-master', 'Developer'],
    technologies: [
      'HTML5',
      'SASS',
      'JS',
      'Handlebars',
      'REST API',
      'AJAX',
      'Parcel',
    ],
    img: require('../img/books/book1.png'),
    link: 'https://slipuykamin.github.io/books-project/index.html',
    anotherImg: [
      require('../img/books/book1.png'),
      require('../img/books/book2.png'),
      require('../img/books/book3.png'),
      require('../img/books/book4.png'),
    ],
  },
  {
    id: 3,
    title: 'Web Studio',
    description: 'A website with hybrid (responsive-adaptive) layout.',
    role: ['Personal project'],
    technologies: ['HTML5', 'SASS', 'JS'],
    img: require('../img/web-studio/webStudio1.png'),
    link: 'https://vasheslav.github.io/goit-markup-hw-08/',
    anotherImg: [
      require('../img/web-studio/webStudio1.png'),
      require('../img/web-studio/webStudio2.png'),
      require('../img/web-studio/webStudio3.png'),
      // require('../img/web-studio/web-studio3.jpg'),
      // require('../img/web-studio/web-studio4.jpg'),
      // require('../img/web-studio/web-studio5.jpg'),
    ],
  },
  {
    id: 4,
    title: 'Ice Cream',
    description: '',
    role: [' Scrum-master', 'Developer'],
    technologies: ['HTML5', 'SASS', 'JS'],
    img: require('../img/iceCream/ice1.png'),
    link: 'https://anna010622.github.io/team-project/',
    anotherImg: [
      require('../img/iceCream/ice1.png'),
      require('../img/iceCream/ice2.png'),
      require('../img/iceCream/ice3.png'),
      require('../img/iceCream/ice4.png'),
    ],
  },
];

export default ProjectsData;
